### PR TITLE
Introduce a search bar in the scene graph

### PR DESCRIPTION
**Pull request by alxbilger**
Nothing very complex: it just highlights the matching components/Nodes in yellow

image

### CODE REVIEW

**Comment by alxbilger** [comment]
Note that typing `f` in the search bar triggers the "fullscreen" shortcut

**Comment by fredroy** [comment]
> Note that typing `f` in the search bar triggers the "fullscreen" shortcut

Should we add a modifier to enable stuff like this ? (fullscreen,, etc). e,g Ctrl+F ? or Shift+F ?

**Review by fredroy — APPROVED** [review]

**Comment by alxbilger** [comment]
@fredroy I think so yes

**Comment by fredroy** [comment]
> @fredroy I think so yes

okay 👍

**Comment by damienmarchal** [comment]
Yes :)

**Pull request merged**
